repos:
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.21.3 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: 'cloudformation/templates/.*\.(json|yml|yaml)$'
